<fieldset class="form-list">
    <?php $_code=$this->getMethodCode() ?>
    <ul id="payment_form_<?php echo $_code ?>" style="display:none">
        <li>
            <?php echo $this->__('You will be redirected to Mellat Payment when you place an order.') ?><br />
<!--			<img style="padding:10px 15px 15px;" src="<?php echo $this->getPaymentImageSrc(); ?>" alt="<?php echo $this->__('Mellat payment method') ?>" />-->
        </li>
    </ul>
</fieldset>